#!/bin/bash
#Usage to back up /dev/disk1 to ./backup.img from a 16GB SD card:
#   backupAndCompressDiskXToImageFileWithEstimatedTotalSize 1 ./backup.img 16000000000

#if needed:
#brew install pv

sudo pv --size $3 /dev/disk$1 | dd bs=2m of=$2
compress7z $2
